version: "3.9"
   
services:
  web:
    build: .
    container_name: clinical_trial_dev
    command: bash -c "
      python manage.py runserver 0.0.0.0:8000 --settings=POCClinicalTrial.settings.dev
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"

